const express = require("express");
const axios = require("axios");
const cors = require("cors");
const dotenv = require("dotenv");
const crypto = require("crypto");
const { createClient } = require("@supabase/supabase-js");

dotenv.config();

const app = express();

app.use(cors());
app.use(express.json());

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_KEY
);

// Normalize phone — last 10 digits only
const normalizePhone = (phone) =>
  phone.replace(/\D/g, "").slice(-10);

// ─────────────────────────────────────────
/// SEND OTP
// ─────────────────────────────────────────
app.post("/send-otp", async (req, res) => {
  try {
    let { phone } = req.body;

    if (!phone) {
      return res.status(400).json({
        success: false,
        message: "Phone number required",
      });
    }

    phone = normalizePhone(phone);

    if (phone.length !== 10) {
      return res.status(400).json({
        success: false,
        message: "Invalid phone number",
      });
    }

    const response = await axios.post(
      "https://www.fast2sms.com/dev/otp/send",
      {
        mobile: phone,
        otp_id: process.env.FAST2SMS_OTP_ID,
      },
      {
        headers: {
          accept: "application/json",
          authorization: process.env.FAST2SMS_API_KEY,
          "content-type": "application/json",
        },
      }
    );

    if (!response.data?.request_id) {
      return res.status(502).json({
        success: false,
        message: "Failed to send OTP — no request_id returned",
      });
    }

    const requestId = response.data.request_id;

    // Delete any existing session for this phone first
    await supabase
      .from("otp_sessions")
      .delete()
      .eq("phone", phone);

    // Insert new session (id auto-generated by DB via gen_random_uuid())
    const { error } = await supabase
      .from("otp_sessions")
      .insert({
        phone,
        session_id: requestId,
        // created_at handled by DB default now()
      });

    if (error) {
      console.error("OTP session insert error:", error);
      return res.status(500).json({
        success: false,
        message: "Failed to save OTP session",
      });
    }

    return res.json({
      success: true,
      request_id: requestId,
    });

  } catch (err) {
    console.error("SEND OTP ERROR:", err.response?.data || err.message);

    return res.status(500).json({
      success: false,
      message: "Failed to send OTP",
      error: err.response?.data || err.message,
    });
  }
});

// ─────────────────────────────────────────
/// VERIFY OTP
// ─────────────────────────────────────────
app.post("/verify-otp", async (req, res) => {
  try {
    let { phone, otp } = req.body;

    if (!phone || !otp) {
      return res.status(400).json({
        success: false,
        message: "Phone and OTP are required",
      });
    }

    phone = normalizePhone(phone);

    if (phone.length !== 10) {
      return res.status(400).json({
        success: false,
        message: "Invalid phone number",
      });
    }

    // FIX: Added order + limit so multiple rows for same phone don't cause issues
    const { data: sessionData, error: sessionError } = await supabase
      .from("otp_sessions")
      .select("*")
      .eq("phone", phone)
      .order("created_at", { ascending: false })
      .limit(1)
      .maybeSingle();

    if (sessionError) {
      console.error("Session lookup error:", sessionError);
      return res.status(500).json({
        success: false,
        message: "Session lookup failed",
      });
    }

    if (!sessionData) {
      return res.status(400).json({
        success: false,
        message: "OTP session not found or expired",
      });
    }

    // Verify OTP with Fast2SMS
    const response = await axios.post(
      "https://www.fast2sms.com/dev/otp/verify",
      {
        mobile: phone,
        otp: otp,
        otp_id: process.env.FAST2SMS_OTP_ID,
      },
      {
        headers: {
          accept: "application/json",
          authorization: process.env.FAST2SMS_API_KEY,
          "content-type": "application/json",
        },
      }
    );

    // FIX: Check either condition — return true OR status_code 200
    if (
      response.data.return !== true ||
      response.data.status_code !== 200
    ) {
      return res.status(400).json({
        success: false,
        message: "Invalid OTP",
      });
    }

    const now = new Date().toISOString();

    // Check if user already exists
    const { data: existingUser, error: userLookupError } = await supabase
      .from("users")
      .select("id, phone, is_verified")
      .eq("phone", phone)
      .maybeSingle();

    if (userLookupError) {
      console.error("User lookup error:", userLookupError);
      return res.status(500).json({
        success: false,
        message: "User lookup failed",
      });
    }

    let userId;

    if (!existingUser) {
      // New user — create record
      userId = crypto.randomUUID();

      const { error: insertUserError } = await supabase
        .from("users")
        .insert({
          id: userId,
          phone,
          is_verified: true,
          verified_at: now,
          // created_at handled by DB default now()
          // all other profile fields left null — filled during onboarding
        });

      if (insertUserError) {
        console.error("User insert error:", insertUserError);
        return res.status(500).json({
          success: false,
          message: "Failed to create user",
        });
      }
    } else {
      userId = existingUser.id;

      // Existing user — update verification status if needed
      if (!existingUser.is_verified) {
        await supabase
          .from("users")
          .update({ is_verified: true, verified_at: now })
          .eq("id", userId);
      }
    }

    // Delete OTP session regardless of new/existing user
    await supabase
      .from("otp_sessions")
      .delete()
      .eq("phone", phone);

    return res.json({
      success: true,
      message: "OTP verified successfully",
      user_id: userId,
      is_new_user: !existingUser,
    });

  } catch (err) {
    console.error("VERIFY ERROR:", err.response?.data || err.message);

    return res.status(500).json({
      success: false,
      message: "OTP verification failed",
      error: err.response?.data || err.message,
    });
  }
});

// ─────────────────────────────────────────
/// HEALTH CHECK
// ─────────────────────────────────────────
app.get("/", (req, res) => {
  res.json({
    status: "ok",
    service: "Fast2SMS OTP Server",
  });
});

const PORT = process.env.PORT || 5000;

app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});
